const products = [
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    category: "smartphones",
    price: 1199.99,
    originalPrice: 1399.99,
    rating: 4.9,
    reviews: 2341,
    badge: "Bestseller",
    description: "Titanio. Tan resistente, tan ligero. Chip A17 Pro con GPU de 6 núcleos. Sistema de cámara Pro con zoom óptico 5x.",
    specs: ["Chip A17 Pro", "6.7\" Super Retina XDR", "48MP + 12MP + 12MP", "Titanio", "USB-C"],
    img: "https://placehold.co/400x400/1a1a2e/ffffff?text=iPhone+15+Pro",
    stock: 15
  },
  {
    id: 2,
    name: "Samsung Galaxy S24 Ultra",
    category: "smartphones",
    price: 1099.99,
    originalPrice: 1299.99,
    rating: 4.8,
    reviews: 1876,
    badge: "Nuevo",
    description: "Galaxy AI integrado. S Pen incluido. Cámara de 200MP con zoom 100x Space Zoom.",
    specs: ["Snapdragon 8 Gen 3", "6.8\" Dynamic AMOLED 2X", "200MP + 50MP + 10MP", "Titanio", "S Pen"],
    img: "https://placehold.co/400x400/0f3460/ffffff?text=Galaxy+S24+Ultra",
    stock: 8
  },
  {
    id: 3,
    name: "MacBook Pro M3 Pro",
    category: "laptops",
    price: 1999.99,
    originalPrice: 2199.99,
    rating: 4.9,
    reviews: 987,
    badge: "Pro",
    description: "Potencia revolucionaria. Chip M3 Pro con CPU de 11 núcleos y GPU de 14 núcleos. Batería de hasta 22 horas.",
    specs: ["Chip M3 Pro", "14.2\" Liquid Retina XDR", "18GB RAM", "512GB SSD", "Hasta 22h batería"],
    img: "https://placehold.co/400x400/16213e/ffffff?text=MacBook+Pro+M3",
    stock: 5
  },
  {
    id: 4,
    name: "Sony WH-1000XM5",
    category: "audio",
    price: 349.99,
    originalPrice: 399.99,
    rating: 4.8,
    reviews: 4521,
    badge: "Top Rated",
    description: "Cancelación de ruido líder en la industria. 30 horas de batería. Calidad de audio Hi-Res.",
    specs: ["ANC líder industria", "30h de batería", "Bluetooth 5.2", "Hi-Res Audio", "8 micrófonos"],
    img: "https://placehold.co/400x400/533483/ffffff?text=Sony+WH-1000XM5",
    stock: 22
  },
  {
    id: 5,
    name: "iPad Pro 13\" M4",
    category: "tablets",
    price: 1299.99,
    originalPrice: 1499.99,
    rating: 4.9,
    reviews: 654,
    badge: "Nuevo",
    description: "El más delgado de Apple. Chip M4, pantalla Ultra Retina XDR OLED y Apple Pencil Pro.",
    specs: ["Chip M4", "13\" Ultra Retina XDR OLED", "256GB", "Wi-Fi 6E", "Apple Pencil Pro"],
    img: "https://placehold.co/400x400/0f4c81/ffffff?text=iPad+Pro+M4",
    stock: 11
  },
  {
    id: 6,
    name: "NVIDIA RTX 4090",
    category: "componentes",
    price: 1599.99,
    originalPrice: 1799.99,
    rating: 4.9,
    reviews: 1234,
    badge: "Gaming",
    description: "La GPU más potente del mundo. 24GB GDDR6X. Ray Tracing y DLSS 3 para gaming y creación de contenido.",
    specs: ["24GB GDDR6X", "CUDA Cores: 16384", "Ray Tracing", "DLSS 3", "PCIe 4.0"],
    img: "https://placehold.co/400x400/1a0533/ffffff?text=RTX+4090",
    stock: 3
  },
  {
    id: 7,
    name: "Apple Watch Ultra 2",
    category: "wearables",
    price: 799.99,
    originalPrice: 899.99,
    rating: 4.7,
    reviews: 876,
    badge: "Adventure",
    description: "El Apple Watch más potente. Titanio de grado aeroespacial. GPS de doble frecuencia. 60 horas de batería.",
    specs: ["Titanio aeroespacial", "GPS doble frecuencia", "60h batería", "S9 SiP", "Resistente 100m"],
    img: "https://placehold.co/400x400/1c1c1e/ffffff?text=Apple+Watch+Ultra+2",
    stock: 9
  },
  {
    id: 8,
    name: "Dell XPS 15 OLED",
    category: "laptops",
    price: 1799.99,
    originalPrice: 1999.99,
    rating: 4.7,
    reviews: 543,
    badge: "OLED",
    description: "Pantalla OLED 3.5K impresionante. Intel Core i9 de 13.ª gen. Diseño ultradelgado y premium.",
    specs: ["Intel Core i9-13900H", "15.6\" OLED 3.5K", "32GB DDR5", "1TB NVMe", "GeForce RTX 4060"],
    img: "https://placehold.co/400x400/002147/ffffff?text=Dell+XPS+15",
    stock: 7
  },
  {
    id: 9,
    name: "DJI Mini 4 Pro",
    category: "drones",
    price: 759.99,
    originalPrice: 799.99,
    rating: 4.8,
    reviews: 1102,
    badge: "Nuevo",
    description: "Dron compacto con cámara de 4K/60fps. Autonomía de 34 minutos. Omnidireccional obstacle sensing.",
    specs: ["4K/60fps HDR", "34 min autonomía", "Obstacle sensing 360°", "< 249g", "ActiveTrack 360°"],
    img: "https://placehold.co/400x400/4a4e69/ffffff?text=DJI+Mini+4+Pro",
    stock: 14
  },
  {
    id: 10,
    name: "PlayStation 5 Pro",
    category: "gaming",
    price: 699.99,
    originalPrice: 799.99,
    rating: 4.9,
    reviews: 3241,
    badge: "Hot",
    description: "PlayStation 5 Pro con GPU mejorada. Ray Tracing avanzado. 2TB SSD. 8K gaming ready.",
    specs: ["CPU AMD Zen 2 8-Core", "GPU AMD Radeon RDNA 4", "2TB SSD", "Ray Tracing avanzado", "8K ready"],
    img: "https://placehold.co/400x400/00349c/ffffff?text=PS5+Pro",
    stock: 4
  },
  {
    id: 11,
    name: "Samsung Neo QLED 8K 75\"",
    category: "tvs",
    price: 3499.99,
    originalPrice: 3999.99,
    rating: 4.6,
    reviews: 321,
    badge: "8K",
    description: "Televisor Neo QLED 8K con tecnología Quantum Matrix. Procesador Neo Quantum 8K. Dolby Atmos.",
    specs: ["8K 7680x4320", "75\" Neo QLED", "144Hz", "Dolby Atmos", "Game Mode Pro"],
    img: "https://placehold.co/400x400/1e3a5f/ffffff?text=Samsung+Neo+QLED+8K",
    stock: 2
  },
  {
    id: 12,
    name: "Logitech MX Master 3S",
    category: "accesorios",
    price: 99.99,
    originalPrice: 119.99,
    rating: 4.8,
    reviews: 8932,
    badge: "Favorito",
    description: "El ratón más avanzado de Logitech. 8000 DPI, clic silencioso, scroll MagSpeed electromagnético.",
    specs: ["8000 DPI", "Scroll MagSpeed", "Clic silencioso", "USB-C", "Bluetooth + receptor"],
    img: "https://placehold.co/400x400/2d3561/ffffff?text=MX+Master+3S",
    stock: 45
  }
];

const categories = [
  { id: "all", label: "Todos", icon: "🏠" },
  { id: "smartphones", label: "Smartphones", icon: "📱" },
  { id: "laptops", label: "Laptops", icon: "💻" },
  { id: "audio", label: "Audio", icon: "🎧" },
  { id: "tablets", label: "Tablets", icon: "📲" },
  { id: "componentes", label: "Componentes", icon: "🖥️" },
  { id: "wearables", label: "Wearables", icon: "⌚" },
  { id: "gaming", label: "Gaming", icon: "🎮" },
  { id: "drones", label: "Drones", icon: "🚁" },
  { id: "tvs", label: "TVs", icon: "📺" },
  { id: "accesorios", label: "Accesorios", icon: "🖱️" }
];
